SET(CMAKE_SYSTEM_NAME FreeBSD)
SET(CMAKE_COMPILER_IS_GNUCC TRUE)
SET(CMAKE_COMPILER_IS_GNUCXX TRUE)

SET(root_dir $ENV{ALCHEMY_HOME})
SET(CMAKE_C_COMPILER ${root_dir}/achacks/gcc)
SET(CMAKE_CXX_COMPILER ${root_dir}/achacks/g++)


SET(CMAKE_FIND_ROOT_PATH ${root_dir}/achacks)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)


